general {
    # Comando para bloquear cuando se debe bloquear
    lock_cmd = gtklock

    # Antes de dormir: bloquear
    before_sleep_cmd = gtklock

    # Después de despertar: encender DPMS
    after_sleep_cmd = hyprctl dispatch dpms on

    # Asegura que no suspenda antes de que el lock se lance:
    inhibit_sleep = 3
}

# Listeners para diferentes acciones por inactividad

listener {
  timeout = 300                 # 5 minutos
  on-timeout = gtklock          # bloquear por inactividad
  on-resume = hyprctl dispatch dpms on
}

listener {
  timeout = 600                 # 10 minutos
  on-timeout = hyprctl dispatch dpms off  # apagar pantalla (DPMS)
  on-resume = hyprctl dispatch dpms on   # encender cuando vuelva actividad
}

listener {
  timeout = 1800                # 30 minutos
  on-timeout = systemctl suspend  # suspender el sistema
  on-resume = hyprctl dispatch dpms on   # encender cuando vuelva actividad
}

